#%RAML 0.8
---
title: Example API
baseUri: http://localhost:3000
version: v123
/a:
  post:
    body:
      application/x-www-form-urlencoded:
        formParameters:
          from:
             description: FROM1
          to:
             description: TO1
/b:
  post:
    body:
      multipart/form-data:
        formParameters:
          from:
             description: FROM2
          to:
             description: TO2
